-- Dedicated table for structured date exceptions (holidays, blocked hours, special hours).
-- Not stored in configurations.settings — this is the single source of truth for exceptions.

create table if not exists public.date_exceptions (
  id bigint generated by default as identity not null,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  provider_id uuid null,
  name text not null,
  exception_date date not null,
  exception_category text not null default 'custom'
    check (exception_category in ('holiday', 'custom')),
  availability_type text not null
    check (availability_type in ('closed', 'unavailable', 'special_hours')),
  start_time time null,
  end_time time null,
  repeat_yearly boolean not null default false,
  notes text null,
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint date_exceptions_pkey primary key (id),
  constraint date_exceptions_time_range_check check (
    availability_type = 'closed'
    or (start_time is not null and end_time is not null and start_time < end_time)
  )
);

create index if not exists idx_date_exceptions_workspace_date
  on public.date_exceptions (workspace_id, exception_date);

create index if not exists idx_date_exceptions_workspace_provider
  on public.date_exceptions (workspace_id, provider_id);

create index if not exists idx_date_exceptions_workspace_status
  on public.date_exceptions (workspace_id, status);

alter table public.date_exceptions enable row level security;

create policy "Users can view date_exceptions from their workspace"
  on public.date_exceptions for select
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can create date_exceptions for their workspace"
  on public.date_exceptions for insert
  with check (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can update date_exceptions in their workspace"
  on public.date_exceptions for update
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can delete date_exceptions from their workspace"
  on public.date_exceptions for delete
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );
