-- Create contacts table if not exists (with all columns)
create table if not exists public.contacts (
  id bigint generated by default as identity not null,
  workspace_id bigint not null,
  email text null,
  name text null,
  phone text null,
  tags text[] null,
  metadata jsonb null default '{}'::jsonb,
  last_seen timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  city text null,
  state text null,
  country text null,
  constraint contacts_pkey primary key (id),
  constraint contacts_workspace_id_fkey foreign key (workspace_id) references workspaces (id)
) tablespace pg_default;

-- Add location fields to existing contacts table (if columns were missing)
alter table public.contacts add column if not exists city text null;
alter table public.contacts add column if not exists state text null;
alter table public.contacts add column if not exists country text null;

-- Index for workspace queries
create index if not exists idx_contacts_workspace_id on public.contacts(workspace_id);

-- Enable Row Level Security
alter table public.contacts enable row level security;

-- RLS policies: use auth.jwt() to avoid "permission denied for table users"
drop policy if exists "Users can view contacts from their workspace" on public.contacts;
create policy "Users can view contacts from their workspace"
  on public.contacts for select
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

drop policy if exists "Users can create contacts for their workspace" on public.contacts;
create policy "Users can create contacts for their workspace"
  on public.contacts for insert
  with check (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

drop policy if exists "Users can update contacts in their workspace" on public.contacts;
create policy "Users can update contacts in their workspace"
  on public.contacts for update
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

drop policy if exists "Users can delete contacts from their workspace" on public.contacts;
create policy "Users can delete contacts from their workspace"
  on public.contacts for delete
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );
