create table if not exists public.services_list (
  id bigint generated by default as identity not null,
  name character varying not null,
  department_id bigint not null,
  created_at timestamp with time zone not null default now(),
  enabled boolean null default true,
  constraint services_list_pkey primary key (id),
  constraint services_unique unique (name, department_id),
  constraint services_list_department_id_fkey foreign key (department_id) references departments_list (id)
) TABLESPACE pg_default;
