-- User ↔ service assignments (workspace-scoped join table)
create table if not exists public.user_services (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  service_id uuid not null references public.services(id) on delete cascade,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_services_user_id on public.user_services(user_id);
create index if not exists idx_user_services_service_id on public.user_services(service_id);
create index if not exists idx_user_services_workspace_id on public.user_services(workspace_id);

alter table public.user_services enable row level security;

create policy "Users can view user_services from their workspace"
  on public.user_services for select
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can create user_services for their workspace"
  on public.user_services for insert
  with check (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can update user_services in their workspace"
  on public.user_services for update
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can delete user_services from their workspace"
  on public.user_services for delete
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );
