-- User ↔ department assignments (workspace-scoped join table)
create table if not exists public.user_departments (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  department_id bigint not null references public.departments(id) on delete cascade,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_departments_user_id on public.user_departments(user_id);
create index if not exists idx_user_departments_department_id on public.user_departments(department_id);
create index if not exists idx_user_departments_workspace_id on public.user_departments(workspace_id);

alter table public.user_departments enable row level security;

create policy "Users can view user_departments from their workspace"
  on public.user_departments for select
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can create user_departments for their workspace"
  on public.user_departments for insert
  with check (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can update user_departments in their workspace"
  on public.user_departments for update
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );

create policy "Users can delete user_departments from their workspace"
  on public.user_departments for delete
  using (
    workspace_id = (auth.jwt() -> 'user_metadata' ->> 'workspace_id')::bigint
  );
