-- Create professions lookup table (global, not workspace-scoped)
create table if not exists public.professions (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamptz not null default now(),
  constraint professions_pkey primary key (id),
  constraint professions_name_key unique (name)
);

-- Enable RLS
alter table public.professions enable row level security;

-- Anyone authenticated can read professions
create policy "Authenticated users can view professions"
  on public.professions for select
  to authenticated
  using (true);

-- Authenticated users can insert new professions (for "Other" option)
create policy "Authenticated users can insert professions"
  on public.professions for insert
  to authenticated
  with check (true);

-- Seed default professions
insert into public.professions (name) values
  ('Doctor'),
  ('Salon'),
  ('Artist')
on conflict (name) do nothing;
