-- Create departments table for workspace department management
create table if not exists public.departments (
  id bigint generated by default as identity not null,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  name text not null,
  description text null,
  meta_data jsonb null,
  created_at timestamptz not null default now(),
  constraint departments_pkey primary key (id),
  constraint departments_id_key unique (id)
);

-- Add index for workspace_id for faster queries
create index if not exists idx_departments_workspace_id on public.departments(workspace_id);

-- Enable Row Level Security
alter table public.departments enable row level security;

-- Create RLS policies
-- Allow authenticated users to read departments from their workspace
create policy "Users can view departments from their workspace"
  on public.departments for select
  using (
    workspace_id = (
      select (raw_user_meta_data->>'workspace_id')::bigint 
      from auth.users 
      where id = auth.uid()
    )
  );

-- Allow authenticated users to insert departments for their workspace
create policy "Users can create departments for their workspace"
  on public.departments for insert
  with check (
    workspace_id = (
      select (raw_user_meta_data->>'workspace_id')::bigint 
      from auth.users 
      where id = auth.uid()
    )
  );

-- Allow authenticated users to update departments in their workspace
create policy "Users can update departments in their workspace"
  on public.departments for update
  using (
    workspace_id = (
      select (raw_user_meta_data->>'workspace_id')::bigint 
      from auth.users 
      where id = auth.uid()
    )
  );

-- Allow authenticated users to delete departments from their workspace
create policy "Users can delete departments from their workspace"
  on public.departments for delete
  using (
    workspace_id = (
      select (raw_user_meta_data->>'workspace_id')::bigint 
      from auth.users 
      where id = auth.uid()
    )
  );

