-- Global catalog for onboarding department suggestions (not workspace-scoped)
create table if not exists public.departments_list (
  id bigint generated by default as identity not null,
  name text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint departments_list_pkey primary key (id),
  constraint departments_list_name_key unique (name)
);

create index if not exists idx_departments_list_enabled on public.departments_list (enabled);

alter table public.departments_list enable row level security;

-- Authenticated users may only read enabled rows (direct client queries)
create policy "Authenticated users can view enabled departments_list"
  on public.departments_list for select
  to authenticated
  using (enabled = true);

alter table public.professions
  add column if not exists enabled boolean not null default true;
