-- Global onboarding catalog (superadmin-managed), parallel to departments_list
create table if not exists public.professions_list (
  id bigint generated by default as identity not null,
  name text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint professions_list_pkey primary key (id),
  constraint professions_list_name_key unique (name)
);

create index if not exists idx_professions_list_enabled on public.professions_list (enabled);

alter table public.professions_list enable row level security;

create policy "Authenticated users can view enabled professions_list"
  on public.professions_list for select
  to authenticated
  using (enabled = true);

-- Seed catalog from existing global professions (one row per distinct name)
insert into public.professions_list (name, enabled)
select distinct on (p.name) p.name, coalesce(p.enabled, true)
from public.professions p
order by p.name, p.id
on conflict (name) do nothing;

-- Repoint departments_list.profession_id from public.professions to public.professions_list
alter table public.departments_list
  add column if not exists profession_list_id bigint references public.professions_list (id) on delete restrict;

update public.departments_list d
set profession_list_id = pl.id
from public.professions p
join public.professions_list pl on lower(trim(pl.name)) = lower(trim(p.name))
where d.profession_id is not null
  and d.profession_id = p.id;

alter table public.departments_list drop constraint if exists departments_list_profession_id_fkey;

drop index if exists departments_list_profession_id_name_uidx;
drop index if exists departments_list_null_prof_name_uidx;
drop index if exists idx_departments_list_profession_id;

alter table public.departments_list drop column if exists profession_id;

alter table public.departments_list rename column profession_list_id to profession_id;

create index if not exists idx_departments_list_profession_id on public.departments_list (profession_id);

create unique index if not exists departments_list_profession_id_name_uidx
  on public.departments_list (profession_id, name)
  where profession_id is not null;

create unique index if not exists departments_list_null_prof_name_uidx
  on public.departments_list (name)
  where profession_id is null;
